title: Cypress MongoDB
description: Plugin that allows interaction with MongoDB server using Cypress commands.
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one